### ISSUE TITLE
Problem saving tetrahedral mesh with 'Save Project'

### ISSUE THREAD

**Issue by ypauchard** [araex/mitk-gem#32]
Not sure if it is actually a tetrahedral mesh saving problem - it  is.

@araex found that the 'Save Project' is called SceneIO at the MITK level and write for unstructured grids is missing.

Submitted on Jan 3, 2017: 
'I have some issues with the MITK-GEM software. If I want to store what I have worked on, it does not store the tetrahedral mesh. I attached the error message of MITK-GEM. Do you know what the problem is?'

![errormeldung_tetrahedal mesh](https://cloud.githubusercontent.com/assets/12809436/21615763/291d1b20-d19c-11e6-852b-e32ff9cbaf07.PNG)

Update on Jan 4, 2017:
Same happens on MacOSX:

> INFO|Wed Jan  4 08:24:42 2017 ||/Users/admin/TC/buildAgent/work/1b4b341ba65bea09/build/MITK/Modules/SceneSerialization/src/mitkSceneIO.cpp(e2)|SaveScene|0|MitkSceneSerialization|Storing scene with 6 objects to /Users/pauc/Desktop/test-image-surface-tetmesh.mitk
> INFO|Wed Jan  4 08:24:42 2017 ||/Users/admin/TC/buildAgent/work/1b4b341ba65bea09/build/MITK/Modules/Core/src/IO/mitkItkImageIO.cpp(173)|Write|0|MitkCore|Writing image: /var/folders/gg/97_t00fn7l967t16dxkyv5c40000gn/T/SceneIOTempUID_20170104152442182904/aaaaaa_input.nrrd
> INFO|Wed Jan  4 08:24:43 2017 ||/Users/admin/TC/buildAgent/work/1b4b341ba65bea09/build/MITK/Modules/Core/src/IO/mitkItkImageIO.cpp(173)|Write|0|MitkCore|Writing image: /var/folders/gg/97_t00fn7l967t16dxkyv5c40000gn/T/SceneIOTempUID_20170104152442182904/baaaaa_input_graphcut_picked.nrrd
> INFO|Wed Jan  4 08:24:43 2017 ||/Users/admin/TC/buildAgent/work/1b4b341ba65bea09/build/MITK/Modules/Core/src/IO/mitkItkImageIO.cpp(173)|Write|0|MitkCore|Writing image: /var/folders/gg/97_t00fn7l967t16dxkyv5c40000gn/T/SceneIOTempUID_20170104152442182904/daaaaa_input_graphcut.nrrd
> ERROR|Wed Jan  4 08:24:43 2017 ||/Users/admin/TC/buildAgent/work/1b4b341ba65bea09/build/MITK/Modules/SceneSerialization/src/mitkSceneIO.cpp(1c3)|SaveBaseData|0|MitkSceneSerialization|No serializer found for UnstructuredGrid. Skipping object
> ERROR|Wed Jan  4 08:24:43 2017 ||/Users/admin/TC/buildAgent/work/1b4b341ba65bea09/build/MITK/Modules/SceneSerializationBase/src/mitkPropertyListSerializer.cpp(7a)|SerializeOneProperty|0|MitkSceneSerializationBase|No serializer found for GridRepresentationProperty. Skipping object
> ERROR|Wed Jan  4 08:24:43 2017 ||/Users/admin/TC/buildAgent/work/1b4b341ba65bea09/build/MITK/Modules/SceneSerializationBase/src/mitkPropertyListSerializer.cpp(7a)|SerializeOneProperty|0|MitkSceneSerializationBase|No serializer found for GridVolumeMapperProperty. Skipping object
> WARN|Wed Jan  4 08:24:44 2017 ||/Users/admin/TC/buildAgent/work/1b4b341ba65bea09/build/MITK/Plugins/org.mitk.gui.qt.ext/src/QmitkExtFileSaveProjectAction.cpp(9d)|Run|0|org_mitk_gui_qt_ext|The following nodes could not be serialized:
>  - UnstructuredGrid contained in node 'tetrahedral mesh'
> WARN|Wed Jan  4 08:24:44 2017 ||/Users/admin/TC/buildAgent/work/1b4b341ba65bea09/build/MITK/Plugins/org.mitk.gui.qt.ext/src/QmitkExtFileSaveProjectAction.cpp(ad)|Run|0|org_mitk_gui_qt_ext|The following properties could not be serialized:
>  - GridRepresentationProperty associated to key 'grid representation'
>  - GridVolumeMapperProperty associated to key 'volumerendering.mapper'

**Comment by araex** [comment]
SceneIO serializer for unstructured grids added with 02934032178f8ac517ea9935dbe89d9d9dcc1180 .
