### ISSUE TITLE
qtWebEngine

### ISSUE THREAD

**Issue by Celli119** [araex/mitk-gem#33]
I've been trying to build the master branch but it requires _qtWebEngine_. I couldn't find this library packaged for ubuntu 16.04 and I get weird errors when I try to build WebEngine : `no matching function for call to ‘QMenu::addAction(QString, QApplication*, void (&)())`.
Then, the question is, how did you solve the **WebEngine dependency for linux** ? Or could you **build a beta 2016.3 release** ?

**Comment by araex** [comment]
You need Qt 5.4 or 5.5. You can check the installed version using `qmake --version`. I'm not sure if you can get those versions via the ubuntu repositories, so you might have to install it using the Qt installer: https://www.qt.io/download-open-source/

Hope that helps
