### ISSUE TITLE
gridcut and licensing

### ISSUE THREAD

**Issue by Celli119** [araex/mitk-gem#35]
I've just wrapped [gridCut](http://gridcut.com/) which is really **faster** and much more **memory effcient**. The problem is I don't know how to manage the **licensing part**. If you have any idea on the way to legally plug it  into mitk-gem, I would be glad to pull request this new feature.
Otherwise, if we find a way, we could even imagine to implement the multi-label graphCut using the new features of MITK 2016.11 & the multi-label graphCut support of [gridCut](http://gridcut.com/).

**Comment by araex** [comment]
Wow, cool to see someone working on this! GridCut sounds promising, i'm especially excited about the lower memory usage, BK maxflow really is taxing on the system! Multi-label graphcuts sound great too, i can see some applications for that.

However, on their license page it says we're not allowed to redistribute it under the free license so it won't be that straight forward. Maybe we can get in contact with them and figure something out? I'll look into it.

**Comment by Celli119** [comment]
Sure, you can still ask them, it would be great we got a license agreement, otherwise we won't have a choice but doing like they did [here](https://github.com/johannesu/gridcut-matlab).

**Comment by araex** [comment]
Yes, i think the best course of action is to make it optional for now. That is mitk-gem uses BK maxflow by default unless the user downloads the gridcut library. Binary distribution would of course use the BK maxflow. 

I'm not sure how to get a conditional compilation like that working within the MITK plugin build system, but i'm sure we can figure it out. Can you open a pull request for your MaxFlowGridCut? I'll look into how to get the build system working when i get the chance to.

**Comment by Celli119** [comment]
I can pull request but I'll have to completely reorder things as the expected structure for gridCut is a bit different. That way we will support all graphCut libaries.

This is the way I see things:
The image3DGraphCutFilter will no longer fill the graph or the output image, this will be the role of children classes organized that way:
- GraphSolver
      -KolmogorovBoostSolver (inherited from GraphSolver)
              -KolmogorovSolver (inherited from KolmogorovBoostSolver)
              -BoostSolver (inherited from KolmogorovBoostSolver)
      -GridCutSolver (inherited from GraphSolver)

These GraphSolverType classes will fill the graph,  solve it, end return the output image that was given by image3DGraphCutFilter

**Comment by ypauchard** [comment]
I got a fast and friendly response from Ondrej at GridCut.

They would like us to have people go to their website to download the code from them. They are thinking about putting GridCut on Github in the near future, which would allow us to either incorporate as a submodule or use CMake's superbuild capability (preferred). I am waiting to hear back on an estimated date.

Unfortunately, we are not allowed to distribute executables that use GridCut unless we purchase the commercial license.

Your thoughts?

**Comment by Celli119** [comment]
I think we have 2 solutions:

-The more simple one would be to use curl and cmake (I don't know if we really can do that).
-The second would be to tell the user to download from the website the package and unzip it into the appropriate folder.

Of course a git repo would be the most suitable solution.

There might be a more efficient (open source) library than maxFlow 3.0  [here](https://github.com/15pengyi/JF-Cut). Problem is, they don't speak about memory efficiency but I guess they took ideas from the gridCut algorithm as they refer it.

**Comment by araex** [comment]
I don't think automatically downloading it during the build is allowed by their license. For now i set it up like this:
If the user extracts the GridCut.zip into the `GraphCut3D/lib/gridcut` directory, the CMake configure step will pick that up and generate a file `lib/gridcut/config.h` that contains a precompiler define. Depending on that, the graphcut plugin will swap out the implementation. 

Thanks for your help @Celli119 ! I played around with a for a little bit and the improved memory efficiency is definitely noticeable which is a huge plus! However, i did not observe any improvements in terms of calculation speed. I had a quick look and it appears that the load is not balanced very well across the spawned threads. About 80% of total time is spent in 1 thread while the rest just waits. I'm not sure if this is a limitation of the algorithm or if there's some other issue. Can you say anything about that @Celli119 ?

**Comment by Celli119** [comment]
- You're right about the CMake part, this will be the cleanest way.

- I guess the speed improvement will depend on the blocksize you set [here](https://github.com/araex/mitk-gem/blob/master/Plugins/ch.zhaw.graphcut/src/internal/lib/GraphCut3D/ImageGridCutFilter.hxx#L32). I've chosen to set this value to 100 which seems to be quite good for the left femur data. I've observed on that example that kolmogorov algorithm took 10 sec against 2.5 for gridCut.
There might be a way to set automatically an appropriate blocksize.

You can also try the non multi-threaded version of gridCut replacing [this header](https://github.com/araex/mitk-gem/blob/master/Plugins/ch.zhaw.graphcut/src/internal/lib/GraphCut3D/ImageGridCutFilter.h#L14) with this one: _GridGraph_3D_6C_. For this one I'm pretty sure about the speed improvement for large images.

**Comment by ypauchard** [comment]
Thanks @araex and @Celli119 for all your work. Just played around with it and I see both speed improvement and memory reduction. This is great!
