### ISSUE TITLE
how to build GEM in windows 10(lack of CGAL)

### ISSUE THREAD

**Issue by leoshaolong** [araex/mitk-gem#43]
I have a problem when I build this project in windows 10, there is a problem about CGAL. I have installed CGAL in my computer, but  it still come out a problem said lack of package CGAL. How to solve this problem.

**Comment by ypauchard** [comment]
Without knowing too much about your setup, you can do the following:

1) Verify CGAL is installed on your system and locate it (path)
2) Make sure CMAKE knows where CGAL is, i.e. if the path is not set in cmake, try and set it manually.

Cheers!

**Comment by ypauchard** [comment]
Ah, I forgot, but CGAL is build as part of the superbuild and it is set in araex/MITK. It looks for GMP and MPFR which are installed when you install CGAL.

Maybe best to try and configure araex/MITK:
```
git clone git@github.com:araex/MITK.git
git checkout mitk-gem
```
then use CMake to build this version of MITK. When you configure, it will ask for QT and then try and find GMP and MPFR. If this configuration succeeds, your installation should work. Can you please try and report back?

**Comment by leoshaolong** [comment]
You mean use Cmake to build this version of MITK first, and then use Cmake to build MITK-GEM with choosing this version of MITK in Cmake configuration?

**Comment by leoshaolong** [comment]
I have build the MITK from source code https://github.com/araex/MITK.git, but this MITK is lack of CGAL too, I can't find CGAL in your CMakeLists.txt document or CMakeExternals.

**Comment by ypauchard** [comment]
Well, for now just build araex/MITK the mitk-gem branch, not master. I just wanted to see if CMake picks up your GMP and MPFR (pre-reqs for CGAL). CGAL will be build as part of the superbuild.
