### ISSUE TITLE
the problems when build MITK-mitk-gem

### ISSUE THREAD

**Issue by leoshaolong** [araex/mitk-gem#44]
In order to build mitk-gem, I need to build MITK-mitk-gem from https://github.com/araex/MITK.git,which include CGAL configuration. But I met some problems in building this version of MITK. 
<img width="480" alt="1" src="https://user-images.githubusercontent.com/23473577/41586380-29458724-739c-11e8-9417-d76adf20fe83.png">
<img width="473" alt="2" src="https://user-images.githubusercontent.com/23473577/41586388-2dd938da-739c-11e8-95d8-b1e6c0cc58fb.png">
<img width="335" alt="3" src="https://user-images.githubusercontent.com/23473577/41586467-58d71264-739c-11e8-9230-c30ee354d9b0.png">

**Comment by ypauchard** [comment]
It seems to be looking for BOOST. I am wondering if it is the mitk-gem branch specifically that causes problem.

Are you able to build any MITK? This master or the current version from mitk.org?

Which CMake version are you using?

**Comment by leoshaolong** [comment]
@ypauchard I can build the current version from mitk.org, when I use the same Prerequisites to build the araex/MITK mitk-gem branch from your website, then I met these problems.

**Comment by leoshaolong** [comment]
@ypauchard The CMake version is 3.6.3

**Comment by leoshaolong** [comment]
@ypauchard Does this MITK version of araex/MITK mitk-gem branch use MSVC2017? Cause I have met this problem: loading initial cache file D:/GEM/GemMitk/bin/ep/tmp/GLEW-cache-Debug.cmake
  -- The C compiler identification is MSVC 17.0.61030.0

**Comment by ypauchard** [comment]
OK, good, you are able to build the mitk.org build. 

I am not too familiar with the windows build, but I think we used windows 7 and MSVC 13.
@araex @diegura would you have some insight into why the windows build fails?

An easy thing to try would be to use a newer version of CMake. I know on other OS this sometimes makes a difference.

I'll try and get my hands on a windows system and try it too.

**Comment by leoshaolong** [comment]
@ypauchard I can build it correctly only in the situation that disable the CGAL. So I think it's the problem of CGAL Plugin.

**Comment by ypauchard** [comment]
OK, thank you for investigating this.

@araex @diegura any thoughts on why this fails on Windows 10?

**Comment by araex** [comment]
Did you  try to use a prebuilt version of CGAL as recommended? The error message you got suggests you're trying to build CGAL as part of the MITK-GEM superbuild. CGAL can be tricky to build on windows and they do not support MSVC 17 according to their [documentation](https://doc.cgal.org/latest/Manual/installation.html#title5). It would be much easier to download a CGAL release and configure the MITK-GEM build to use that.
