### ISSUE TITLE
Command Line Segmentation Tool

### ISSUE THREAD

**Issue by DudleA** [araex/mitk-gem#48]
I followed the instructions on http://araex.github.io/mitk-gem-site/ (FAQ section) for using the CLI.
If I got it right, I have to run a file named "GraphCutSegmentation", however I cannot find it in the downloaded folder after extraction. Is there anything else I have to install, or do I have to build from source?

**Comment by ypauchard** [comment]
I do not believe that we have the CLI pre-compiled in the package we distribute. The FAQ might not be accurate.

You could compile the executable yourself. Which operating system are you working on?

**Comment by DudleA** [comment]
Thanks for your answer. I will then try to compile it myself on Linux (Ubuntu 18).
