### ISSUE TITLE
how to deploy MITK(build) application like GEM in windows10?

### ISSUE THREAD

**Issue by stormyl** [araex/mitk-gem#49]
hello,I'm very confused by how to deploy MITK-app ?
I had build My MITK-application （debug is ok,but release occur to problem:QWidget:Must construct a QApplication before a QWidget) like GEM ,but I don't know how to make .exe or .zip file，can someone give me a suggestion?Thanks!
I can't find out above problem .

**Comment by ypauchard** [comment]
For a general MITK based application using the newest MITK version, the MITK wiki page has some information on this:
https://docs.mitk.org/nightly/DeploymentPage.html

If you still have problems, I strongly suggest asking this question in the MITK mailinglist:
https://www.mitk.org/wiki/MITK_Mailinglist
