### ISSUE TITLE
Qt5.5 is no longer available

### ISSUE THREAD

**Issue by thsmit** [araex/mitk-gem#50]
It seams like Qt5.5 is no longer available in https://download.qt.io/archive/qt/. Compiling MITK-GEM on Ubuntu 20.04 is giving me troubles when I try another version of Qt, especially with: "Qt5WebKitWidgets" provides a separate development package". Is there a solutions for this problem?

**Comment by ypauchard** [comment]
It looks like there is a new link:

https://download.qt.io/new_archive/qt/5.5/

I hope this works.
