### ISSUE TITLE
Ct-Calibration using a K2HPO4-Phantom

### ISSUE THREAD

**Issue by BrMatMa** [araex/mitk-gem#52]
Hi, I am currently trying to perform Ct-calibration using a K2HPO4-Phantom and I am struggeling to find the relation between ρ_ct density mg dipotassium phosphate per cc and mg hydroxyapatite per cc . Does anyone know how to convert mg dipotassium phosphate per cc to mg hydroxyapatite per cc?

**Comment by ypauchard** [comment]
In the first step, Hounsfield units are converted to calibration densities $\rho_{ct}$. Note that $\rho_{ct}$ can be in mg K2HPO4/ccm. You would then need to find the corresponding $\rho_{ct}\rightarrow\rho_{ash}$ formula. A few relationships are summarized in this article:

Knowles, Nikolas K., Jacob M. Reeves, and Louis M. Ferreira. 2016. “Quantitative Computed Tomography (QCT) Derived Bone Mineral Density (BMD) in Finite Element Studies: A Review of the Literature.” Journal of Experimental Orthopaedics 3 (December): 36. https://doi.org/10.1186/s40634-016-0072-2.

For conversion between phantoms, $\text{HA} =1.15 \cdot \text{K2HPO4} - 7.32$ is reported in:

Faulkner, K. G., C. C. Glüer, S. Grampp, and H. K. Genant. 1993. “Cross-Calibration of Liquid and Solid QCT Calibration Standards: Corrections to the UCSF Normative Data.” Osteoporosis International: A Journal Established as Result of Cooperation between the European Foundation for Osteoporosis and the National Osteoporosis Foundation of the USA 3 (1): 36–42.

**Comment by BrMatMa** [comment]
Thank you very much @ypauchard!
